server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0 #索引
    host: 127.0.0.1
    port: 6379
    password: redis #修改成对应自己的redis密码
    lettuce:
        pool:
            max-active: 8 #最大连接数
            max-idle: 8 #最大空闲连接
            min-idle: 0 #最小空闲连接